const GeoLayout Bbh_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(16, geo_switch_area),
		GEO_OPEN_NODE(),
			GEO_BRANCH(1, Bbh_dl_1_geo),
			GEO_BRANCH(1, Bbh_dl_10_geo),
			GEO_BRANCH(1, Bbh_dl_11_geo),
			GEO_BRANCH(1, Bbh_dl_12_geo),
			GEO_BRANCH(1, Bbh_dl_13_geo),
			GEO_BRANCH(1, Bbh_dl_14_geo),
			GEO_BRANCH(1, Bbh_dl_15_geo),
			GEO_BRANCH(1, Bbh_dl_2_geo),
			GEO_BRANCH(1, Bbh_dl_3_geo),
			GEO_BRANCH(1, Bbh_dl_4_geo),
			GEO_BRANCH(1, Bbh_dl_5_geo),
			GEO_BRANCH(1, Bbh_dl_6_geo),
			GEO_BRANCH(1, Bbh_dl_7_geo),
			GEO_BRANCH(1, Bbh_dl_8_geo),
			GEO_BRANCH(1, Bbh_dl_9_geo),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout Bbh_dl_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ghost_house_1_dl_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout Bbh_dl_10_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ghost_house_3_dl_mesh),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ghost_house_2_dl_mesh),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ghost_house_painting_dl_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout Bbh_dl_11_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ghost_house_3_dl_mesh),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ghost_house_4_dl_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout Bbh_dl_12_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ghost_house_1_dl_mesh),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ghost_house_7_dl_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout Bbh_dl_13_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ghost_house_7_dl_mesh),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ghost_house_8_dl_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout Bbh_dl_14_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ghost_house_1_dl_mesh),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ghost_house_5_dl_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout Bbh_dl_15_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ghost_house_5_dl_mesh),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ghost_house_6_dl_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout Bbh_dl_2_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ghost_house_painting_dl_mesh),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ghost_house_2_dl_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout Bbh_dl_3_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ghost_house_3_dl_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout Bbh_dl_4_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ghost_house_4_dl_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout Bbh_dl_5_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ghost_house_5_dl_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout Bbh_dl_6_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ghost_house_6_dl_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout Bbh_dl_7_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ghost_house_7_dl_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout Bbh_dl_8_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ghost_house_8_dl_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout Bbh_dl_9_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ghost_house_1_dl_mesh),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ghost_house_2_dl_mesh),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ghost_house_painting_dl_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout Bbh_area_1[] = {
    GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
    GEO_OPEN_NODE(),
        GEO_ZBUFFER(0),
        GEO_OPEN_NODE(),
            GEO_NODE_ORTHO(100),
            GEO_OPEN_NODE(),
                GEO_BACKGROUND_COLOR(0x0001),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_ZBUFFER(1),
        GEO_OPEN_NODE(),
            GEO_CAMERA_FRUSTUM_WITH_FUNC(45, 50, 10000, geo_camera_fov),
            GEO_OPEN_NODE(),
                GEO_CAMERA(4, 0, 2000, 6000, 0, 0, 0, geo_camera_main),
                GEO_OPEN_NODE(),
                    GEO_SWITCH_CASE(16, geo_switch_area),
	                    	GEO_OPEN_NODE(),
	                    		GEO_BRANCH(1, Bbh_dl_1_geo),
	                    		GEO_BRANCH(1, Bbh_dl_10_geo),
	                    		GEO_BRANCH(1, Bbh_dl_11_geo),
	                    		GEO_BRANCH(1, Bbh_dl_12_geo),
                    			GEO_BRANCH(1, Bbh_dl_13_geo),
                    			GEO_BRANCH(1, Bbh_dl_14_geo),
                    			GEO_BRANCH(1, Bbh_dl_15_geo),
                    			GEO_BRANCH(1, Bbh_dl_2_geo),
                    			GEO_BRANCH(1, Bbh_dl_3_geo),
                    			GEO_BRANCH(1, Bbh_dl_4_geo),
                    			GEO_BRANCH(1, Bbh_dl_5_geo),
                    			GEO_BRANCH(1, Bbh_dl_6_geo),
                    			GEO_BRANCH(1, Bbh_dl_7_geo),
                    			GEO_BRANCH(1, Bbh_dl_8_geo),
                    			GEO_BRANCH(1, Bbh_dl_9_geo),
                    		GEO_CLOSE_NODE(),
					GEO_RENDER_OBJ(),
                    GEO_ASM(0, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_ASM(0, AreaMap),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};