// 0x0E000608
const GeoLayout thi_geo_000608[] = {
    GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
    GEO_OPEN_NODE(),
        GEO_ZBUFFER(0),
        GEO_OPEN_NODE(),
            GEO_NODE_ORTHO(100),
            GEO_OPEN_NODE(),
                GEO_BACKGROUND(BACKGROUND_HAUNTED, geo_skybox_main),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_ZBUFFER(1),
        GEO_OPEN_NODE(),
            GEO_CAMERA_FRUSTUM_WITH_FUNC(45, 100, 20000, geo_camera_fov),
            GEO_OPEN_NODE(),
                GEO_CAMERA(1, 0, 2000, 6000, 0, 0, 0, geo_camera_main),
                GEO_OPEN_NODE(),
                    GEO_DISPLAY_LIST(LAYER_OPAQUE, big_world_1_dl_mesh),
                    GEO_DISPLAY_LIST(LAYER_OPAQUE, big_world_2_dl_mesh),
                    GEO_DISPLAY_LIST(LAYER_ALPHA, big_world_3_dl_mesh),
                    GEO_DISPLAY_LIST(LAYER_TRANSPARENT, big_world_4_dl_mesh),
                    GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, big_world_5_dl_mesh),
                    GEO_ASM(   0, geo_movtex_pause_control),
                    GEO_ASM(0x1301, geo_movtex_draw_water_regions),
                    GEO_RENDER_OBJ(),
                    GEO_ASM(   0, geo_envfx_main),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_ZBUFFER(0),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_cannon_circle_base),
            GEO_ASM(3, AreaMap),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};
